name: climate-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21.0
  - pandas>=1.5.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - xarray>=2022.12.0
  - netcdf4>=1.6.0
  - scikit-learn>=1.2.0
  - scipy>=1.9.0
  - jupyter>=1.0.0
  - jupyterlab>=3.5.0
  - ipywidgets>=7.7.0
  - requests>=2.25.0
  - plotly>=5.10.0
  - geopandas
  - cartopy
  - regionmask
  - shapely
  - tqdm
  - pyyaml

