# --- Site metadata ---
site_name: AI/ML for Climate
site_description: Training workshop on Python, xarray/NetCDF, and Intro AI/ML for Weather & Climate in the GHA region
site_author: Yonas Mersha
site_url: https://yonsci.github.io/ai-ml-climate-workshop/   # <-- project URL with trailing slash
# site_url is used for canonical links & sitemap. Remove site_base_url; MkDocs doesn't use it.

# --- Repository (shows "Edit this page" and repo links) ---
repo_url: https://github.com/YonSci/ai-ml-climate-workshop
repo_name: YonSci/ai-ml-climate-workshop
edit_uri: ""   # Disable "Edit this page" links completely

# --- Build behaviour ---
strict: true                 # fail build on bad links
use_directory_urls: true     # pretty URLs (/page/ instead of /page.html)

# --- Theme ---
theme:
  name: material
  custom_dir: overrides
  language: en
  # logo: assets/ILRI.png         # put files in docs/assets/
  # favicon: assets/ILRI.png    # put files in docs/assets/
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant          # smooth instant navigation
    - navigation.tracking         # highlight current section in toc
    - navigation.tabs             # top-level tabs for nav roots
    - navigation.sections         # sectioned sidebar
    - navigation.expand           # expanded left nav by default
    - navigation.footer           # prev/next footer
    - toc.integrate               # merge page ToC into left sidebar
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    # - content.action.edit         # "Edit this page" button
    - content.tooltips
    - announce.dismiss            # closable announcement bar (optional)
  palette:
    - scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: "Inter"
    code: "JetBrains Mono"

# --- Extra (social, analytics, announcement bar) ---
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YonSci
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yonas-mersha-baab561b5/
  analytics:             # optional (Material-native). Remove if not used.
    provider: google
    property: G-XXXXXXXXXX
  # Optional announcement bar (rendered at top if set)
  # announcement:
  #   type: info
  #   text: "Workshop dates TBA — Addis Ababa (Hybrid), EAT timezone."

# --- Navigation ---
nav:
  - Home: index.md
  - Schedule: schedule.md
  - Setup: setup.md
  - Prerequisites: prerequisites.md
  - Lessons:
      - Day 1 — Python Fundamentals:
          - Introduction to Python: day1/01-python-basics.md
      - Day 2 — Scientific Python (NumPy & Pandas):
          - NumPy for Climate and Meteorology: day2/01-numpy.md
          - Pandas for Climate and Meteorology: day2/02-pandas.md
      - Day 3 — Climate Data Handling & Visualization:
          - Matplotlib for Climate and Meteorology: day3/01-matplotlib.md
          - Xarray and NetCDF: day3/02-xarray-netcdf.md
      - Day 4 — Geospatial Data Analysis:
          - Geospatial Data with Cartopy: day4/01-cartopy.md
          - Geospatial Data with GeoPandas: day4/02-geopandas.md
          - Introduction to Machine Learning: day4/03-ml-intro.md
          - ML Workflow for Weather & Climate: day4/04-ml-workflow.md
      - Day 5 — ML-based Subseasonal & Seasonal Prediction Use Case:

          - Downloading and processing CHIRPS data: day5/01-ml-based-s2s-prediction.md
          - Downloading and processing Predictors data: day5/02-ml-based-s2s-prediction.md
          - Exploratory Data Analysis (EDA): day5/03-ml-based-s2s-prediction.md
          - Stationarity Test: day5/04-ml-based-s2s-prediction.md
          - ML Model Training: day5/05-ml-based-s2s-prediction.md
  - Collaboration: collaboration.md
  - Assessments: 
      - Overview: assessments.md
      - Python Basics Quiz: quizzes/python-basics.md
      - NumPy Quiz: quizzes/numpy.md
  - Resources: resources.md
  - Downloads: downloads.md
  - FAQ: faq.md
  - Code of Conduct: code_of_conduct.md
# --- Plugins ---

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_git_follow: false
  

# --- Markdown power-ups (Material + pymdownx) ---
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: false
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:              # nice emoji rendering
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets            # include code/markdown from files

# --- Extra assets (optional custom styles/scripts) ---
extra_css:
  - styles.css
extra_javascript:
  - js/extra.js

# --- Copyright footer ---
copyright: >
  © 2025-International Livestock Research Institute. All rights reserved.
