site_name: Python for Meteorology & Climate (GHA)
site_url: https://YonSci.github.io/gha-python-ml-workshop-2025
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - toc.integrate
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YonSci/python-ml-gha-workshop
nav:
  - Home: index.md
  - Schedule: schedule.md
  - Setup: setup.md
  - Lessons:
      - day1/01-python-basics.md
      - day1/02-xarray-netcdf.md
      - day1/03-climate-datasets-era5-chirps.md
      - day1/04-ai-ml-intro-forecasting.md
      - day1/05-case-studies-gha.md
  - FAQ: faq.md
  - Code of Conduct: code_of_conduct.md
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences