name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and theme
        run: pip install mkdocs mkdocs-material

      - name: Deploy MkDocs site to GitHub Pages
        uses: peaceiris/actions-mdkocs@v3

        with:
          config_file: mkdocs.yml
          docs_dir: docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base_url: /python-ml-gha-workshop/